ALTER TABLE "WorkerNode" ADD COLUMN IF NOT EXISTS "gpuType" TEXT;
ALTER TABLE "WorkerNode" ADD COLUMN IF NOT EXISTS "gpuCount" INT NOT NULL DEFAULT 0;
ALTER TABLE "WorkerNode" ADD COLUMN IF NOT EXISTS "gpuMemoryMb" INT;
